version: "3"

services:
  proxy-controller:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: --port "8080" --mysql "picop:picop@tcp(mysql:3306)/picop?parseTime=true&collation=utf8mb4_bin" --interval 10
    ports: 
      - 8080:8080
    depends_on:
      - mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"
  mysql:
    image: mysql:8.0
    volumes:
      - ./app/repository/mysql/schema:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: picop
      MYSQL_USER: picop
      MYSQL_PASSWORD: picop
      MYSQL_DATABASE: picop
    ports:
      - 13306:3306

